- name: Build and push Backend
  uses: docker/build-push-action@v5
  with:
    context: ./skillswap/backend    # CHANGE THIS
    push: true
    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/skillswap-backend:latest

- name: Build and push Frontend
  uses: docker/build-push-action@v5
  with:
    context: ./skillswap/frontend    # CHANGE THIS
    push: true
    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/skillswap-frontend:latest